[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app = { path = "../app", default-features = false, features = ["ssr"] }
leptos = { workspace = true, features = [ "ssr" ]}
leptos_axum.workspace = true

axum.workspace = true
simple_logger.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http = { workspace = true, features = ["cors", "fs"] }
log.workspace = true
thiserror.workspace = true

sqlx.workspace = true
uuid.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
leptos_config = "0.8.2"
dotenvy = "0.15"
mime_guess = "2"

[dev-dependencies]
http.workspace = true
serial_test.workspace = true
